Quicker client disconnection handling to prevent UID conflict on reconnection (#41)
* Remove client UID immediately when client is marked for destruction

* Make BrokerUidManager threadsafe

* Add #include "etcpal/cpp/lock.h" to UID manager header

* Switch etcpal::RwLock to std::unique_ptr<etcpal::RwLock>

Fixes error C2280.

* Make sure RwLock is allocated

* On device reboot, make sure clients removed is called before clients added

* Use default member initializer for uid_manager_lock_

* Rename "uid_manager_lock_" to "lock_"